symbol: BTC/USDT
verbose: true

binance:
  api_key: paste your binance api key here
  api_secret: paste your binance api secret here
  dataset_max_days: 7 # maximum amount of days to include in the dataset (to train the model)
  
trade:
  test: true
  amount: 50
  profit_percentage: 10 # 10%

telegram:
  bot_token: 123456789:blablabla
