symbol: BTC/USDT
verbose: true

binance:
  api_key: paste your binance api key here
  api_secret: paste your binance api secret here
  
trade:
  test: true
  symbol: BTC/USDT
  amount: 50
  profit_percentage: 10 # 10%
